packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  consola: ^3.4.2
  typescript: 5.9.2
  
  # Common devDependencies
  vitest: 3.2.4
  eslint: ^9.35.0
  bunchee: ^6.6.0
  "@types/node": 24.3.1
  "@vitest/coverage-v8": 3.2.4
  "@vitest/ui": 3.2.4
  prettier: ^3.6.0
  turbo: ^2.5.6
  vite: 7.1.4
  "@vitejs/plugin-vue": 6.0.1
  happy-dom: 18.0.1
  
  # ESLint-related dependencies
  "@eslint/js": ^9.31.0
  "@next/eslint-plugin-next": ^15.4.2
  "eslint-config-prettier": ^10.1.1
  "eslint-plugin-only-warn": ^1.1.0
  "eslint-plugin-react": ^7.37.5
  "eslint-plugin-react-hooks": ^5.2.0
  "eslint-plugin-turbo": ^2.5.0
  "globals": ^16.3.0
  "typescript-eslint": ^8.37.0
