packages:
  - apps/*
  - packages/*
  - packages/resolvers/*

catalog:
  '@eslint/js': ^9.31.0
  '@next/eslint-plugin-next': ^15.4.2
  '@types/node': 24.3.1
  '@vitejs/plugin-vue': 6.0.1
  '@vitest/coverage-v8': 3.2.4
  '@vitest/ui': 3.2.4
  '@types/semver': 7.7.1
  bunchee: ^6.6.0
  consola: ^3.4.2
  eslint: ^9.35.0
  eslint-config-prettier: ^10.1.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.0
  globals: ^16.3.0
  happy-dom: 18.0.1
  prettier: ^3.6.2
  turbo: ^2.5.6
  typescript: 5.9.2
  typescript-eslint: ^8.37.0
  vite: 7.1.4
  vitest: 3.2.4
